<?php

namespace App\Services;

class SeedGenerator
{
    /**
     * Create a new class instance.
     */
    public function __construct()
    {
        //
    }

    public static function createRandomHtml() : string
    {
        $backgroundColor = rand(0x000000, 0xFFFFFF);
        $randomNumber = random_int(0, 1000000);
        return <<<EOT
        <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Random HTML with PHP</title>
                <style>
                    body {
                        background-color: $backgroundColor
                        font-family: Arial, sans-serif;
                        display: flex;
                        justify-content: center;
                        align-items: center;
                        min-height: 100vh;
                        margin: 0;
                        color: white; /* For better contrast with random backgrounds */
                        text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
                    }
                    .content {
                        text-align: center;
                        padding: 20px;
                        border-radius: 10px;
                        background-color: rgba(0, 0, 0, 0.3); /* Semi-transparent overlay */
                    }
                    h1 {
                        font-size: 3em;
                        margin-bottom: 10px;
                    }
                    p {
                        font-size: 1.5em;
                    }
                </style>
            </head>
            <body>
                <div class="content">
                    <h1>Welcome to a Random Page!</h1>
                    <p>Your lucky random number is: <strong>$randomNumber<strong></p>
                    <p>This page has a random background color generated by PHP.</p>
                </div>
            </body>
            </html>
        EOT;
    }
}
